In [1]:
import numpy as np

In [3]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [6]:
A = np.random.randn(10)
A

array([ 1.22147559, -1.1202888 ,  1.35748677, -0.45601736, -0.61203204,
       -0.95589613,  1.15118066, -1.14403859, -0.58640305, -0.34034463])

In [7]:
B = np.random.randn(10)
B

array([-1.30386772, -1.25685918, -1.22955681,  1.56735397, -1.66640527,
       -1.63606428, -0.45711038,  1.31812139,  0.09670643,  0.28309853])

In [8]:
# Binary Functions
np.add(A,B)

array([-0.08239213, -2.37714798,  0.12792996,  1.11133661, -2.27843731,
       -2.59196041,  0.69407028,  0.1740828 , -0.48969662, -0.05724611])

In [9]:
np.maximum(A,B)

array([ 1.22147559, -1.1202888 ,  1.35748677,  1.56735397, -0.61203204,
       -0.95589613,  1.15118066,  1.31812139,  0.09670643,  0.28309853])